_wandb:
    value:
        cli_version: 0.24.1
        e:
            eqabn1qlxs724ousg1n3lb90vlj4xbb5:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1081101176832"
                        used: "22372552704"
                email: made2806@colorado.edu
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-c99e9e6e-d495-5dd9-a0a3-ae39456de5cc
                host: LAPTOP-B7654087
                memory:
                    total: "7191330816"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /mnt/c/Users/manda/Desktop/Projects/RL Locomotion Control/train.py
                python: CPython 3.10.12
                root: /mnt/c/Users/manda/Desktop/Projects/RL Locomotion Control
                startedAt: "2026-02-03T05:35:10.561711Z"
                writerId: eqabn1qlxs724ousg1n3lb90vlj4xbb5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.12
            "5": 0.24.1
            "12": 0.24.1
            "13": linux-x86_64
algorithm:
    value: SAC
batch_size:
    value: 256
ent_coef:
    value: auto
env_id:
    value: HalfCheetah-v5
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
learning_starts:
    value: 10000
num_envs:
    value: 4
seed:
    value: 42
tau:
    value: 0.005
total_timesteps:
    value: 1000000
